fastgram/fastgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('users/', include('users.urls', namespace='users')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('response/', include('response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls))
    ]

fastgram/response/urls.py
from django.urls import path

from response import views

app_name = 'response'

urlpatterns = [
    path(
        '',
        views.ListResponsesView.as_view(),
        name='list_responses',
        ),
    path(
        'response_detail/<int:pk>/',
        views.ResponseDetailView.as_view(),
        name='response_detail',
        ),
    path(
        'like/<int:response_id>/?page=<int:page_number>/'
        '&is_detail=<str:is_detail>/',
        views.LikeResponseView.as_view(),
        name='like',
        ),
    path(
        'comment/<int:response_id>/?page=<int:page_number>/'
        '&is_detail=<str:is_detail>/',
        views.CommentResponse.as_view(),
        name='comment',
        ),
]

fastgram/users/urls.py
from django.conf import settings
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users import views as local_views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
        ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logout.html',
        ),
        name='logout',
        ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
        ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
        ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('users:password_reset_done'),
            email_template_name='users/password_reset_email.html',
            from_email=settings.ADMIN_EMAIL,
        ),
        name='password_reset',
        ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done',
        ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm',
        ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
        ),
    path(
        'sign_up/',
        local_views.SignUpView.as_view(),
        name='sign_up',
        ),
    path(
        'profile/',
        local_views.ProfileView.as_view(),
        name='profile',
    ),
]

fastgram/response/models.py
from ckeditor.fields import RichTextField
from core.models import ImageBaseModel, NameBaseModel
from django.db import models
from django.urls import reverse

from response.managers import CommentManager, ResponseManager
from users.models import CustomUser


class Delivery(NameBaseModel):
    another_link = models.URLField(
        'другие отзывы',
        max_length=200,
        null=True,
        blank=True,
        help_text='Добавьте ссылку на сайт с отзывами об этой службе',
        )

    class Meta:
        verbose_name = 'курьерская служба'
        verbose_name_plural = 'курьерские службы'


class Response(NameBaseModel):
    delivery = models.ForeignKey(
        Delivery,
        verbose_name='курьерская служба',
        on_delete=models.CASCADE,
        help_text='Выберите курьерскую службу',
        )
    text = RichTextField(
        'описание',
        help_text='Подробно расскажите о впечатлениях от данной'
        ' курьерской службы',
        )
    created_on = models.DateTimeField(
        'дата написания',
        auto_now_add=True,
        )
    user = models.ForeignKey(
        CustomUser,
        verbose_name='пользователь',
        on_delete=models.CASCADE,
        related_name='user_response',
        )
    likes = models.ManyToManyField(
        CustomUser,
        verbose_name='лайк',
        blank=True,
        )

    class Grades(models.IntegerChoices):
        NEGATIVE = 1, 'Отрицательная'
        NORMAL = 2, 'Нейтральная'
        POSITIVE = 3, 'Положительная'

    grade = models.IntegerField(
        'оценка',
        choices=Grades.choices,
        blank=True,
        null=True,
        )

    objects = ResponseManager()

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'
        ordering = ['-created_on']

    def get_absolute_url(self):
        return reverse('response:response_detail', kwargs={'pk': self.pk})


class MainImage(ImageBaseModel):
    response = models.OneToOneField(
        Response,
        verbose_name='отзыв',
        on_delete=models.CASCADE,
        null=True,
        )

    class Meta:
        verbose_name = 'изображение'
        verbose_name_plural = 'изображения'


class Comment(models.Model):
    text = RichTextField(
        'текст',
        help_text='Напишите свой комментарий',
        )
    user = models.ForeignKey(
        CustomUser,
        verbose_name='пользователь',
        on_delete=models.CASCADE,
        )
    response = models.ForeignKey(
        Response,
        verbose_name='отзыв',
        on_delete=models.CASCADE,
        )

    objects = CommentManager()

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return f'{self.user} к "{self.response}"'

fastgram/response/forms.py
from django import forms

from response.models import Comment, MainImage, Response


class MainImageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = MainImage
        fields = (
            MainImage.image.field.name,
        )


class ResponseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Response
        fields = (
            Response.name.field.name,
            Response.delivery.field.name,
            Response.text.field.name,
            Response.grade.field.name,
        )
        widgets = {
            Response.text.field.name: forms.Textarea(attrs={
                'rows': 5,
            }),
        }


class CommentForm(forms.ModelForm):
    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = (
            Comment.text.field.name,
        )
        widgets = {
            Comment.text.field.name: forms.Textarea()
        }

fastgram/response/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import FormMixin
from response.forms import CommentForm, MainImageForm, ResponseForm
from response.models import Comment, MainImage, Response


class ListResponsesView(FormMixin, ListView):
    model = Response
    model_image = MainImage
    model_comment = Comment
    form_class = ResponseForm
    form_image_class = MainImageForm
    comment_form_class = CommentForm
    template_name = 'response/list_responses.html'
    paginate_by = 5
    success_url = reverse_lazy('response:list_responses')

    def get_queryset(self):
        queryset = Response.objects.list_responses()
        searched = self.request.GET.get('searched', '').lower()
        print(searched)
        if searched:
            queryset = (
                queryset.
                filter(
                    Q(name__icontains=searched)
                    | Q(delivery__name__icontains=searched)
                    | Q(text__icontains=searched)
                    )
                )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = self.comment_form_class
        context['comments'] = self.model_comment.objects.all_comments()
        context['image_form'] = self.form_image_class(
            self.request.POST or None,
            self.request.FILES,
            )
        return context

    def post(self, request):
        image_form = self.form_image_class(
            self.request.POST or None,
            self.request.FILES,
            )
        form = self.form_class(
            self.request.POST or None
            )
        if self.request.user and image_form.is_valid() and form.is_valid():
            response = self.model.objects.create(
                user=self.request.user,
                **form.cleaned_data,
            )
            self.model_image.objects.create(
                response=response,
                **image_form.cleaned_data,
            )
            return redirect(self.get_success_url())

        return render(request, self.get_success_url(), self.get_context_data())


class LikeResponseView(FormView):
    def get_queryset(self):
        return Response.objects.list_responses()

    def post(self, request, response_id, page_number, is_detail):
        is_detail = is_detail == 'True'
        if is_detail:
            success_url = reverse_lazy(
                'response:response_detail',
                kwargs={'pk': response_id}
            )
        elif page_number:
            success_url = (
                reverse_lazy('response:list_responses')
                + f'?page={page_number}'
                )

        response = get_object_or_404(
            self.get_queryset(),
            id=response_id,
            )

        if request.user in response.likes.all():
            response.likes.remove(request.user)
        else:
            response.likes.add(request.user)
            response.save()
        return redirect(success_url)


class ResponseDetailView(DetailView):
    model_comment = Comment
    comment_form_class = CommentForm
    model = Response
    template_name = 'response/response_detail.html'

    def get_success_url(self, **kwargs):
        if kwargs is not None:
            return reverse_lazy(
                'response:response_detail',
                kwargs={'pk': kwargs['pk']}
            )
        return reverse_lazy('response:response_detail')

    def get_queryset(self):
        return Response.objects.list_responses()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = self.comment_form_class
        context['comments'] = self.model_comment.objects.all_comments()
        return context


class CommentResponse(FormView):
    model = Comment

    def post(self, request, response_id, page_number, is_detail):
        is_detail = is_detail == 'True'
        if is_detail:
            success_url = reverse_lazy(
                'response:response_detail',
                kwargs={'pk': response_id}
                )
        elif page_number:
            success_url = (
                reverse_lazy('response:list_responses')
                + f'?page={page_number}'
                )
        form = CommentForm(request.POST or None)
        if form.is_valid():
            self.model.objects.create(
                user=request.user,
                response=Response.objects.get(id=response_id),
                **form.cleaned_data,
            )
        return redirect(success_url)

fastgram/templates/response/includes/add_comments.html
<div class="d-inline-block p-1 mx-2">
  <button
    type="button"
    class="btn btn-dark text-nowrap"
    data-bs-toggle="modal"
    data-bs-target="#modal-comment{{ response.id }}">
    Комментарии
    </button>
    <div
    class="modal fade"
    id="modal-comment{{ response.id }}"
    tabindex="-1"
    aria-labelledby="commentModalLabel"
    aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header bg-dark text-white">
            <h5 class="modal-title" id="commentModalLabel">
              Комментарии
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close">
            </button>
          </div>
          <div class="modal-body text-dark">
            <div>
              {% for comment in comments %}
                {% if response.id == comment.response.id %}
                  <div class="border border-2 rounded border-dark p-3 mb-3">
                    <h6 class="border-bottom pb-2">{{ comment.user }}</h3>
                    <p>{{ comment.text }}</p>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            {% if page_obj %}
              <form
                action={% if 'response_detail' in request.path %} 
                       {% url 'response:comment' response_id=response.id page_number=page_obj.number is_detail=True %}
                       {% else %}
                       {% url 'response:comment' response_id=response.id page_number=page_obj.number is_detail=False %}
                       {% endif %}
                method="post"
                class="d-inline-block">
            {% else %}
              <form
              action={% if 'response_detail' in request.path %} 
                     {% url 'response:comment' response_id=response.id page_number=0 is_detail=True %}
                     {% else %}
                     {% url 'response:comment' response_id=response.id page_number=0 is_detail=False %}
                     {% endif %}
              method="post"
              class="d-inline-block">
            {% endif %}
              {% csrf_token %}
              {{ comment_form.as_p }}
              <button type="submit" name="comment" class="btn btn-dark mx-sm-3 w-25 ">
                Опубликовать
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

fastgram/templates/response/includes/add_response.html
{% if user.is_authenticated %}
<button
  type="button"
  class="btn btn-dark text-nowrap"
  data-bs-toggle="modal"
  data-bs-target="#modal-cart"
>
  Добавить отзыв
</button>
<div
  class="modal fade"
  id="modal-cart"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header bg-dark text-white">
        <h5 class="modal-title" id="exampleModalLabel">Ваш отзыв</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body text-dark">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          {{ image_form.as_p }}
          <button type="submit" class="btn btn-dark mx-sm-3 w-25">
            Опубликовать
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}

fastgram/templates/response/includes/card.html
{% load static %}

{% load thumbnail %}

<div class="container mt-3 text-dark">
  {% with response.grade as grade %}
    <div class="card mb-3"
        style="background:
        {% if grade == 3 %} lightgreen
        {% elif grade == 1 %} #FF8080
        {% endif %};">
  {% endwith %}
      <div class="card-header">
        {% thumbnail response.user.image "32x32" crop="center" as im %}
          <img src="{{ im.url }}"
              width="{{ im.width }}"
              height="{{ im.height }}"
              alt="Фото профиля"
              class="rounded-circle z-depth-0"
            >
        {% endthumbnail %}
        {{ response.user.email }}
      </div>
      <div class="card-body text-dark">
        <h5 class="card-title">{{ response.name }}</h5>
          <em> Курьерская служба: </em>{{ response.delivery.name }}
            {% thumbnail response.mainimage.image "200x200" crop="center" as im %}
              <img src="{{ im.url }}"
                  width="{{ im.width }}"
                  height="{{ im.height }}"
                  class="rounded float-end"
                  alt="Картинка к отзыву"
                >
            {% endthumbnail %}
            {% with request.resolver_match.view_name as view_name %}
              {% if view_name == 'response:response_detail' %}
                {{ response.text|safe }}
                <p><a href="{% url 'response:list_responses' %}" class="btn btn-dark" style="color: #26ded2">Назад</a></p>
              {% else %}
                {% if response.text|slice:":3" != '<p>' %}
                  <p>{{ response.text|safe|truncatewords:40 }}</p>
                {% else %}
                    {{ response.text|safe|truncatewords:40 }}
                {% endif %}
                {% if response.text|length > 40 %}
                  <p><a href="{{ response.get_absolute_url }}" class="btn btn-dark" style="color: #26ded2">Читать больше...</a></p>
                {% endif %}
              {% endif %}
                
            {% endwith %}
          <p><a href="{{ response.delivery.another_link }}">
            Вы можете ознакомиться с другими отзывами об этой службе
          </a></p>        
      </div> 
      <div class="d-inline-block p-1 mx-2 block">
        {% if page_obj %}
          <form
            action={% if 'response_detail' in request.path %} 
                   {% url 'response:like' response_id=response.id page_number=page_obj.number is_detail=True %}
                   {% else %}
                   {% url 'response:like' response_id=response.id page_number=page_obj.number is_detail=False %}
                   {% endif %}
            method="post"
            class="d-inline-block">
        {% else %}
          <form
          action={% if 'response_detail' in request.path %} 
                 {% url 'response:like' response_id=response.id page_number=0 is_detail=True %}
                 {% else %}
                 {% url 'response:like' response_id=response.id page_number=0 is_detail=False %}
                 {% endif %}
          method="post"
          class="d-inline-block">
        {% endif %}
          {% csrf_token %}
            <button type="submit" class="border-0 button">
              {% if user in response.response_likes  %}
                <img class="image" src={% static 'img/like_red.png' %} alt="Лайк!">
              {% else %}
                <img class="image" src={% static 'img/like.png' %} alt="Лайк!">
              {% endif %}
            </button>
        </form>
        <div class="text-black d-inline-block">{{ response.response_likes|length }}</div>
      </div>

      {% include 'response/includes/add_comments.html' %}

      <div class="card-footer text-dark">
        {{ response.created_on }}
      </div>
    </div>
  </div>

fastgram/templates/response/includes/pagination.html
<ul class="nav justify-content-center pagination">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a
      class="btn btn-outline-light rounded-circle"
      style="color: #26ded2"
      href="?page={{ page_obj.previous_page_number }}"
      >&laquo;
    </a>
  </li>
  <li class="page-item">
    <a
      class="btn btn-outline-light rounded-circle"
      style="color: #26ded2"
      href="?page={{ page_obj.previous_page_number }}"
      >{{ page_obj.previous_page_number }}
    </a>
  </li>
  {% endif %}
  <li class="page-item active">
    <a
      class="btn active btn-outline-light rounded-circle"
      style="color: #26ded2"
    >
      <span class="current">{{ page_obj.number }}</span>
    </a>
  </li>
  {% if page_obj.has_next %}
  <li class="page-item">
    <a
      class="btn btn-outline-light rounded-circle"
      style="color: #26ded2"
      href="?page={{ page_obj.next_page_number }}"
      >{{ page_obj.next_page_number }}
    </a>
  </li>
  <li class="page-item">
    <a
      class="btn btn-outline-light rounded-circle"
      style="color: #26ded2"
      href="?page={{ page_obj.next_page_number }}"
      >&raquo;
    </a>
  </li>
  {% endif %}
</ul>

fastgram/templates/response/includes/search.html
<form
  class="col-12 d-flex col-lg-auto mb-3 mb-lg-0 me-lg-3"
  method="get"
  action="{% url 'response:list_responses' %}"
>
  {% csrf_token %}
  <input
    name="searched"
    type="search"
    class="form-control form-control-dark me-2"
    placeholder="Поиск..."
    aria-label="Search"
  >
  <button class="btn btn-outline-light" style="color: #26ded2">Найти</button>
</form>