fastgram/fastgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('users/', include('users.urls', namespace='users')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('response/', include('response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls))
    ]

fastgram/users/urls.py
from django.conf import settings
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users import views as local_views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
        ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logout.html',
        ),
        name='logout',
        ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
        ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
        ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('users:password_reset_done'),
            email_template_name='users/password_reset_email.html',
            from_email=settings.ADMIN_EMAIL,
        ),
        name='password_reset',
        ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done',
        ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm',
        ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
        ),
    path(
        'sign_up/',
        local_views.SignUpView.as_view(),
        name='sign_up',
        ),
    path(
        'profile/',
        local_views.ProfileView.as_view(),
        name='profile',
    ),
]

fastgram/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone

from core.models import ImageUserBaseModel
from users.managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin, ImageUserBaseModel):
    first_name = models.CharField(
        'имя',
        max_length=150,
        blank=True,
        null=True,
        )
    last_name = models.CharField(
        'фамилия',
        max_length=150,
        blank=True,
        null=True,
        )
    email = models.EmailField(
        'почта',
        unique=True,
        )
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.email

fastgram/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    password = None

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'image')

fastgram/users/views.py
import os

from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import FormView

from users.forms import CustomUserChangeForm, CustomUserCreationForm
from users.models import CustomUser


class SignUpView(FormView):
    template_name = 'users/sign_up.html'
    model = CustomUser
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, FormView):
    template_name = 'users/profile.html'
    model = CustomUser
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('users:profile')

    def get_form(self):
        return self.form_class(
               self.request.POST or None,
               self.request.FILES,
               instance=self.request.user,
               )

    def form_valid(self, form):
        old_image = CustomUser.objects.get(id=self.request.user.id).image
        if old_image:
            image_path = old_image.path
            if os.path.exists(image_path):
                os.remove(image_path)
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class(
            initial=self.initial,
            instance=self.request.user,
            )
        return context

fastgram/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    <title>Вход</title>
{% endblock %}

{% block content %}
<div>
    <h1 class="text-center mt-3">Вход</h1>
    {% include 'users/includes/form.html' %}
</div>
{% endblock %}

fastgram/templates/users/logout.html
{% extends 'base.html' %}

{% block title %}
    <title>Выход из аккаунта</title>
{% endblock %}

{% load static %}
{% block content %}
<h1 class="text-center" >Вы вышли из аккаунта</h1>
<div class="col-md-8 mx-auto text-center mt-3">
    <img
        src="{% static 'img/logout.jpeg' %}"
        height="165"
        alt="Возвращайся скорее :("
        class="d-block mx-auto mb-3"
        >
</div>
{% endblock %}

fastgram/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}
    <title>Изменение пароля</title>
{% endblock %}

{% block content %}
<h1 class="text-center">Изменение пароля</h1>
{% include 'users/includes/form.html' %}
{% endblock %}

fastgram/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}
    <title>Изменение пароля</title>
{% endblock %}

{% block content %}
<h1 class="text-center">Пароль успешно изменен</h1>
{% endblock %}

fastgram/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}
    <title>Восстановление пароля</title>
{% endblock %}

{% block content %}
<h2 class="text-center mt-3">Восстановление пароля</h2>
<p class="col-md-4 mx-auto text-center mt-3">
    Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам
    инструкцию, как установить новый пароль.
</p>
{% include 'users/includes/form.html' %}
{% endblock %}

fastgram/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
    <title>Восстановление пароля</title>
{% endblock %}

{% block content %}
<br>
<div class="container text-center">
  <p class="mx-sm-2 lead mb-4">
    Ваш пароль установлен. Вы можете войти в систему сейчас
  </p>
  <a href="{% url 'users:login' %}" class="btn btn-dark mx-sm-3">Перейти ко входу</a>
</div>
{% endblock %}

fastgram/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    <title>Восстановление пароля</title>
{% endblock %}

{% block content %}
<h1 class="text-center"> Восстановление пароля </h1>
{% include 'users/includes/form.html' %}
{% endblock %}

fastgram/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    <title>Восстановление пароля</title>
{% endblock %}

{% block content %}
<h2 class="text-center mt-3">
  Письмо с инструкциями по восстановлению пароля отправлено
</h2>
<p class="col-md-4 mx-auto text-center mt-3">
  Мы отправили вам инструкцию по установке нового пароля на указанный адрес
  электронной почты (если в нашей базе данных есть такой адрес). Вы должны
  получить ее в ближайшее время. Если вы не получили письмо, пожалуйста,
  убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте
  папку со спамом.
</p>
{% endblock %}

fastgram/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

fastgram/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    <title>Профиль</title>
{% endblock %}

{% block content %}
    <h1 class="text-center">Профиль</h1>
    {% include 'users/includes/user_card.html'%}
    <div class="container mx-sm-4 mb-3 mt-3">
    <a href="{% url 'users:password_change' %}" class="btn btn-dark mx-sm-3">Сменить пароль</a>
    <button
      type="button"
      class="btn btn-dark"
      data-bs-toggle="modal"
      data-bs-target="#modal-cart"
    >
      Редактировать Данные
    </button>
    <div
      class="modal fade"
      id="modal-cart"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-xl text-dark">
        <div class="modal-content">
          <div class="modal-header bg-dark text-white">
            <h5 class="modal-title" id="exampleModalLabel">
              Редактирование профиля
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            {% include 'users/includes/form.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

fastgram/templates/users/sign_up.html
{% extends 'base.html' %}

{% block title %}
    <title>Регистрация</title>
{% endblock %}

{% block content %}
<h1 class="text-center mt-3">Регистрация</h1>
{% include 'users/includes/form.html' %}
{% endblock %}