fastgram/delivery/urls.py
from delivery import views
from django.urls import path

app_name = 'delivery'

urlpatterns = [
    path('', views.DeliveryView.as_view(), name='delivery'),
    path('shows', views.DeliveryShowView.as_view(), name='show'),
    path('taxi', views.DeliveryTaxiView.as_view(), name='taxi'),
]

fastgram/fastgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('users/', include('users.urls', namespace='users')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('response/', include('response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls))
    ]

fastgram/feedback/urls.py
from django.urls import path

from feedback import views

app_name = 'feedback'

urlpatterns = [
    path('', views.FeedbackView.as_view(), name='feedback'),
]

fastgram/homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

fastgram/response/urls.py
from django.urls import path

from response import views

app_name = 'response'

urlpatterns = [
    path(
        '',
        views.ListResponsesView.as_view(),
        name='list_responses',
        ),
    path(
        'response_detail/<int:pk>/',
        views.ResponseDetailView.as_view(),
        name='response_detail',
        ),
    path(
        'like/<int:response_id>/?page=<int:page_number>/'
        '&is_detail=<str:is_detail>/',
        views.LikeResponseView.as_view(),
        name='like',
        ),
    path(
        'comment/<int:response_id>/?page=<int:page_number>/'
        '&is_detail=<str:is_detail>/',
        views.CommentResponse.as_view(),
        name='comment',
        ),
]

fastgram/users/urls.py
from django.conf import settings
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users import views as local_views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
        ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logout.html',
        ),
        name='logout',
        ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
        ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
        ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('users:password_reset_done'),
            email_template_name='users/password_reset_email.html',
            from_email=settings.ADMIN_EMAIL,
        ),
        name='password_reset',
        ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done',
        ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm',
        ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
        ),
    path(
        'sign_up/',
        local_views.SignUpView.as_view(),
        name='sign_up',
        ),
    path(
        'profile/',
        local_views.ProfileView.as_view(),
        name='profile',
    ),
]

fastgram/templates/includes/footer.html
<footer class="my-footer">
  <div class="container">
    <p class="text-center text-muted">© {% now "Y" %} Product by SRS</p>
  </div>
</footer>

fastgram/templates/includes/header.html
{% load static %}

{% load thumbnail %}
<header class="p-2 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <img
            src={% static 'img/mainicon.png' %}
            class="bi me-2"
            width="52"
            height="44"
            alt="Иконка сайта"
            aria-label="Bootstrap"
          >
        </a>
        {% with request.resolver_match.view_name as view_name %}
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'homepage:home' %}"
              class="nav-link px-2
              {% if view_name == 'homepage:home' %} text-secondary disabled
              {% else %} li_active text-white {% endif %}">О нас</a></li>
            <li><a href="{% url 'delivery:delivery' %}"
              class="nav-link px-2
              {% if view_name == 'delivery:delivery' %} text-secondary disabled
              {% else %} li_active text-white {% endif %}">Доставки</a></li>
            <li><a href="{% url 'response:list_responses' %}"
              class="nav-link px-2
              {% if view_name == 'response:list_responses' %} text-secondary disabled
              {% else %} li_active text-white {% endif %}">Отзывы по доставкам</a></li>
            <li><a href="{% url 'feedback:feedback' %}"
              class="nav-link px-2
              {% if view_name == 'feedback:feedback' %} text-secondary disabled
              {% else %} li_active text-white {% endif %}">Обратная связь</a></li>
          </ul>
          {% if view_name == 'response:list_responses' %}
            {% include 'response/includes/search.html' %}
          {% endif %}
        
          <div class="text-end">
            {% if user.is_authenticated %}
              {% with request.resolver_match.view_name as view_name %}
                <div class="dropdown">
                  {% if user.image %}
                    {% thumbnail user.image "32x32" crop="center" as im %}
                      <img src="{{ im.url }}"
                        width="{{ im.width }}"
                        height="{{ im.height }}"
                        class="rounded-circle z-depth-0 dropdown-toggle"
                        role="button"
                        alt="Фото профиля"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        >
                    {% endthumbnail %}
                  {% else %}
                  <img src="{% static 'img/blank-avatar.jpeg' %}"
                    width="32"
                    height="32"
                    class="rounded-circle z-depth-0 dropdown-toggle"
                    role="button"
                    alt="Фото профиля"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                  {% endif %}
                    <div class="dropdown-menu">
                      {% if view_name != 'users:profile' %}
                        <a href="{% url 'users:profile' %}" class="dropdown-item text-dark" style="color: #26ded2">Профиль</a>
                      {% endif %}
                      <a href="{% url 'users:logout' %}" class="dropdown-item text-danger">Выйти</a>
                    </div>
                </div>
              {% endwith %}
            {% else %}
              <a href="{% url 'users:login' %}"
              class="btn btn-outline-light me-2"
              style="color: #26ded2">Вход</a>
              <a href="{% url 'users:sign_up' %}"
              class="btn btn-outline-light me-2"
              style="color: #26ded2">Регистрация</a>
            {% endif %} 
        </div>
        {% endwith %}
      </div>
    </div>
</header>