fastgram/delivery/urls.py
from delivery import views
from django.urls import path

app_name = 'delivery'

urlpatterns = [
    path('', views.DeliveryView.as_view(), name='delivery'),
    path('shows', views.DeliveryShowView.as_view(), name='show'),
    path('taxi', views.DeliveryTaxiView.as_view(), name='taxi'),
]

fastgram/fastgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls', namespace='delivery')),
    path('users/', include('users.urls', namespace='users')),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('response/', include('response.urls', namespace='response')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls))
    ]

fastgram/users/urls.py
from django.conf import settings
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from users import views as local_views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login',
        ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logout.html',
        ),
        name='logout',
        ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done'),
        ),
        name='password_change',
        ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
        ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy('users:password_reset_done'),
            email_template_name='users/password_reset_email.html',
            from_email=settings.ADMIN_EMAIL,
        ),
        name='password_reset',
        ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done',
        ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete'),
        ),
        name='password_reset_confirm',
        ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete',
        ),
    path(
        'sign_up/',
        local_views.SignUpView.as_view(),
        name='sign_up',
        ),
    path(
        'profile/',
        local_views.ProfileView.as_view(),
        name='profile',
    ),
]

fastgram/delivery/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Delivery(models.Model):
    weight = models.FloatField(
        'вес',
        validators=[MinValueValidator(0.1), MaxValueValidator(30)],
        help_text='Введите вес посылки от 0.1 до 1400 кг',
        default=0.1,
        )
    length = models.IntegerField(
        'длина',
        validators=[MinValueValidator(1), MaxValueValidator(120)],
        help_text='Введите высоту посылки от 1 до 120 см',
        )
    width = models.IntegerField(
        'ширина',
        validators=[MinValueValidator(1), MaxValueValidator(80)],
        help_text='Введите высоту посылки от 1 до 80 см',
        )
    height = models.IntegerField(
        'высота',
        validators=[MinValueValidator(1), MaxValueValidator(50)],
        help_text='Введите высоту посылки от 1 до 50 см',
        )
    cost = models.IntegerField(
        'стоимость посылки',
        validators=[MinValueValidator(500), MaxValueValidator(200000)],
        help_text='Введите стоимость посылки от 500 до 200000 рублей',
        default=1000,
        )
    city_from = models.CharField(
        'город отправки посылки',
        max_length=50,
        help_text='Максимум 50 символов'
        )
    city_to = models.CharField(
        'город получения посылки',
        max_length=50,
        help_text='Максимум 50 символов'
        )

fastgram/delivery/forms.py
from delivery.models import Delivery

from django import forms


class DeliveryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Delivery
        fields = '__all__'

fastgram/delivery/views.py
from django.conf import settings
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from delivery.delivery_calcultaion import CalculateBoxberry, CalculateLPost
from delivery.forms import DeliveryForm
from delivery.models import Delivery


class DeliveryView(FormView):
    template_name = 'delivery/delivery.html'
    template_name_for_show_deliveries = 'delivery/show_deliveries.html'
    model = Delivery
    form_class = DeliveryForm
    success_url = reverse_lazy('delivery:show')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apikey'] = settings.YANDEX_MAPS_API_KEY
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            form_params = form.cleaned_data
            weight = form_params['weight']
            length = form_params['length']
            width = form_params['width']
            height = form_params['height']
            cost = form_params['cost']
            city_from = form_params['city_from'].capitalize()
            city_to = form_params['city_to'].capitalize()
            try:
                l_post_delivery = CalculateLPost(
                    weight, length, width, height,
                    cost, city_from, city_to
                    )
                calculate_l_post = l_post_delivery.calculate_l_post()
            except KeyError:
                calculate_l_post = []
            try:
                boxberry_delivery = CalculateBoxberry(
                    weight, length, width,
                    height, cost, city_from,
                    city_to
                    )
                calculate_boxberry = boxberry_delivery.calculate_boxberry()
            except KeyError:
                calculate_boxberry = []

            return render(
                request,
                self.template_name_for_show_deliveries,
                {
                    'args_l_post': calculate_l_post,
                    'args_boxberry': calculate_boxberry,
                    }
                )

        return render(
            request,
            self.template_name_for_show_deliveries,
            )


class DeliveryShowView(TemplateView):
    template_name = 'delivery/show_deliveries.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apikey'] = settings.YANDEX_MAPS_API_KEY
        return context


class DeliveryTaxiView(TemplateView):
    template_name = 'delivery/taxi_deliveries.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apikey'] = settings.YANDEX_MAPS_API_KEY
        return context

fastgram/templates/delivery/delivery.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
<title>Маршрут от точки на карте</title>
{% endblock title %}

{% block content %}
<h1 class="text-center mt-3">Стоимость доставки</h1>
<p class="text-center">Заполните форму для получения стоимости доставки</p>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group col-sm-4 mx-auto mb-2">
    {{ field.label_tag }}
    {{ field }}
    {{ field.message.id }}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
    {% if field.errors %}
    <div class="alert alert-danger">{{ field.errors }}</div>
    {% endif %}
  </div>
  {% endfor %}
  <div class="col text-center">
    <button type="submit" class="btn btn-dark mx-sm-3">Отправить</button>
  </div>
</form>
{% endblock content %}

fastgram/templates/delivery/route_panel_control.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  <title>Маршрут от точки на карте</title>
{% endblock title %}

{% block add_css_link %}
    <link rel="stylesheet" href={% static "css/route_panel_control.css" %}>
{% endblock add_css_link %}

{% block content %}
    <h1 class="text-center mt-3 ">Сравнение стоимости доставки</h1>
    <div class="delivery_map" id="map"></div>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=40d1649f-0493-4b70-98ba-98533de7710b" type="text/javascript"></script>
    <script src="https://yandex.st/jquery/2.2.3/jquery.min.js" type="text/javascript"></script>
    <script src={% static 'js/route_panel_control.js' %} type="text/javascript"></script>
{% endblock content %}

fastgram/templates/delivery/show_deliveries.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Расчет доставок</title>
{% endblock title %}

{% block add_css_link %}
    <link rel="stylesheet" href={% static "css/delivery.css" %}>
{% endblock add_css_link %}

{% block content %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey={{ apikey }}" type="text/javascript"></script>
    <script src="https://yandex.st/jquery/2.2.3/jquery.min.js" type="text/javascript"></script>
    <div class="text-center">
        <h1>Стоимость доставки</h1>
        <h4 style="color: #26ded2" class="mt-3">Компании доставок для себя</h4>
        <table class='table-info table mx-auto' style="max-width: 65%;" border="1">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Компания</th>
                    <th scope="col">Специализация</th>
                    <th scope="col">Доставка курьером</th>
                    <th scope="col">Доставка до пункта выдачи</th>
                    <th scope="col">Ссылка</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Boxberry</td>
                    <td>Универсальные доставки</td>
                    {% if args_boxberry %}
                        {% for args in args_boxberry %}
                            <td>{{ args }}</mark>
                        {% endfor %}
                    {% else %}
                        <td>Отсутствует(возможно стоит перепроверить форму)</td>
                        <td>Отсутствует(возможно стоит перепроверить форму)</td>
                    {% endif %}
                    <td><a href='https://boxberry.ru/'>Сайт</a></td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>L-post</td>
                    <td>Интернет-магазины</td>
                    {% if args_l_post %}
                        {% for args in args_l_post %}
                            <td>{{ args }}</mark>
                        {% endfor %}
                    {% else %}
                        <td>Отсутствует(возможно стоит перепроверить форму)</td>
                        <td>Отсутствует(возможно стоит перепроверить форму)</td>
                    {% endif %}
                    <td><a href='https://l-post.ru/'>Сайт</a></td>
                </tr>
            </tbody> 
        </table> 
    </div>
    <div class="text-center">
        <h4 style="color: #26ded2" class='mt-3'>Яндекс доставка</h4>
        <h6>компания специализируется на доставках для бизнеса</h6>
        <h6>доставка производится на грузовых автомобилях, тариф перевозки - 20 рублей за км</h6>
    </div>
    <script src={% static 'js/delivery_yandex.js' %} type="text/javascript"></script>
    <div id="map"></div>
    <br>
    <p class="text-center"><a href="https://dostavka.yandex.ru/">Ссылка на сайт компании</a></p>
    <div class='text-center pt-3'>
        <a class="btn btn-large btn-dark" href={% url 'delivery:taxi' %}>Забрать посылку на такси</a>
    </div>
    <h5 style="color: #26ded2" class='text-center mt-3 fw-weight-bold'>Посмотреть доставку менее популярных сервисов вы можете здесь</h5>
    <ul class="text-center">
        <li><a href="https://calculator-dostavki.ru/">Калькулятор доставки грузов по России</a></li>
        <li><a href="https://vse-dostavki.ru/calc/">Калькулятор грузоперевозок по России</a></li>
    </ul>
    <div class="text-center pb-3">
        <a class="btn btn-large btn-dark" href={% url 'delivery:delivery' %}>Заполнить форму снова</a>
    </div>    
{% endblock content %}

fastgram/templates/delivery/taxi_deliveries.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  <title>Расчет стоимости Такси</title>
{% endblock title %}

{% block add_css_link %}
    <link rel="stylesheet" href={% static "css/delivery.css" %}>
{% endblock add_css_link %}

{% block content %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey={{ apikey }}" type="text/javascript"></script>
    <script src="https://yandex.st/jquery/2.2.3/jquery.min.js" type="text/javascript"></script>
    <script src={% static 'js/route_panel_control.js' %} type="text/javascript"></script>
    <div id="map"></div>
    <div class="text-center pt-3">
        <a class="btn btn-large btn-dark" href={% url 'delivery:delivery' %}>Заполнить форму снова</a>
    </div>
{% endblock content %}